shabados/database

- Dockerfile
- README.md
- package.json
- release.sh
Releases can be properly semverred according to the tag in any commit messages
> Semver releases

- README.md
- lib/models/Lines.js
Orders the results `Lines` provides by default, by:
1) Exact matches
2) First letters
3) Letters anywhere
> Order results in API

- data/Sri Dasam Granth/0011.json
Sirlekh of Akal Ustaat is 2 lines, not one.
> Split Line 2JGF into new line with ID EZH0

- data/banis.json
- Extend Rehraas Sahib
- Add Aartee
- Lavaa(n)
- Akhand Paath Bhog
> Add More Baanis

- data/README.md
- data/Sri Guru Granth Sahib Ji/0132.json
- package-lock.json
> Split Shabad AUS into 2 Shabads

- data/Sri Dasam Granth/0001.json
Source: ਨਿਤਨੇਮ ਤੇ ਹੋਰ ਬਾਣੀਆ, SGPC, May 2017
> Correct ID ZS3Y

- lib/models/Lines.js
- refactor existing search mechanism into genericSearch
> feat(api): add full word searching

- data/Vaaran Bhai Gurdas Ji/37.json
This is a #Patch release
Testing the closing of PRs from CLI
> Release 4.0.16

- data/Vaaran Bhai Gurdas Ji/41.json
> fix(data): corrections to Bhai Gurdaas Ji Vaaran

- lib/models/Banis.js
> fix(api): Fix lines relation in Bani

- data/Sri Guru Granth Sahib Ji/0916.json
> fix(data): Combine Shabad 6CJ into LHY

- data/Ardaas/1.json
> fix(data): fix line 8EEH in Ardaas

- data/Vaaran Bhai Gurdas Ji/04.json
- data/Vaaran Bhai Gurdas Ji/11.json
- data/Vaaran Bhai Gurdas Ji/14.json
- data/Vaaran Bhai Gurdas Ji/17.json
- data/Vaaran Bhai Gurdas Ji/36.json
- data/Vaaran Bhai Gurdas Ji/37.json
- data/Vaaran Bhai Gurdas Ji/38.json
A few remaining issues that need to be closed out
> fix(data): Fix remaining corrections to Bhai Gurdaas Ji Vaaran

- data/Sarabloh Granth/1.json
- data/Sarabloh Granth/2.json
- data/Sarabloh Granth/3.json
- data/Sarabloh Granth/4.json
- data/sources.json
- data/translation_sources.json
- package-lock.json
> feat(data): import Sarabloh Granth

- docker/mariadb/Dockerfile
Instead of hardcoding patch version 10.4.7
> build(docker): Use mariadb:10.4 image

- .circleci/config.yml
- lib/benchmark.js
- lib/models/Banis.js
- lib/models/CommonQueryBuilder.js
- lib/models/Lines.js
- lib/models/Shabads.js
Without translations and transliterations:
```
Running benchmarks
10 samples will be collected
First Letter Searching
hh: 77.6ms (3115 lines)
hhh: 30.5ms (253 lines)
hhhh: 25.9ms (49 lines)
hhhgg: 48.4ms (6 lines)
h_r_p: 55.7ms (40 lines)
Full Word Searching
ihr: 53.1ms (753 lines)
jo jnu: 32ms (21 lines)
Lines
KNCN: 3.7ms
DXUY: 1.9ms
PZ9Q: 2.3ms
LZPR: 2.7ms
QD98: 2ms
XQ82: 1.6ms
Shabads
9AC: 2.6ms (19 lines)
N1W: 2.5ms (15 lines)
GE6: 2.3ms (8 lines)
B6R: 2.1ms (23 lines)
HHZ: 1.6ms (13 lines)
0T2: 1.6ms (7 lines)
All Banis
All Banis: 1.4ms (25 results)
All Bani Lines
Jap Ji Sahib: 15.5ms (385 lines)
Jaap Sahib: 26.4ms (801 lines)
Tav Prasad Svaiyay: 3.5ms (43 lines)
Benti Choupai Sahib: 5.7ms (104 lines)
Anand Sahib: 6.7ms (210 lines)
Anand Sahib (6 Pauris and Salok): 4ms (41 lines) …
```
> Improve retrieval of translations and transliterations

- data/banis.json
Related but not dependent of _Refactor banis as bookmarks, add tags to bookmarks to designate/differentiate #1389_
> feat(data/banis): add commonly read bookmarks

- data/Sri Guru Granth Sahib Ji/0248.json
> fix(data): combine shabad id 0PU and YM8 #1506

- data/Sri Guru Granth Sahib Ji/0368.json
> fix(data): update page number for id 864V #1568

- data/Sri Guru Granth Sahib Ji/0133.json
- package-lock.json
> feat(data): split Barah Maha into separate shabads

- docs/getting-started/introduction.md
- docs/index.html
- docs/usage/overview.md
- lib/generate-id.js
For #147 cannot seem to find out why the homepage is not auto sizing itself because we have meta tags for HTML 5.
Also updates the `lib/generate-id` 
Closes #148
Closes #149 
Closes #1573
> Update docs and generate id script

- data/banis.json
> fix(data): match Aarti baani with one sung at Sri Darbar Sahib

- data/Sri Dasam Granth/0155.json
Aside from partial completion of issue #1450, everything should be done corrections wise for issues 1394 to 1479.
I have not gone through and matched page numbers for lines. Let me know if I should do that, it's in issue #1575 for tracking.
Build breaks because of gurmukhi-utils translit issue
> Sri Dasam Granth - Mehron Corrections for Issues 1394 to 1479

- data/Sri Dasam Granth/0155.json
Replaced open-top yaiya characters with a new character used by ASCII font
nine_thousand_years
Fix #1758
> fix(data): replace open-yaiya characters with new codepoint

- data/Sri Dasam Granth/0155.json
- data/Sri Dasam Granth/0159.json
- data/Sri Dasam Granth/0160.json
- data/Sri Dasam Granth/0161.json
Updated to match Mehron Saroop
> fix(data): update chaubis avtar ang 155-161 Pauri 9 to match source

- .circleci/config.yml
Fixes CI builds to allow for new releases:
- Updates release branch to main
- Skips broken benchmarking suite
> ci: update circleci config to pass builds

- lib/build-database.js
- package-lock.json
- package.json
Updates the 4.x release to the latest gurmukhi utils. Fixes CI build issues. Ported from `next`.
> build: update to gurmukhi-utils@3

- lib/build-database.js
Throws a descriptive error if a gurmukhi line is empty/missing during database build
> build: catch missing gurmukhi during build-database

- .circleci/config.yml
Removes unnecessary step - we have deploy keys set up.
> ci: remove ci builds on main branch

- .circleci/config.yml
- release.sh
Sets git credentials during the docker deploy job
> ci: set git credentials during docker image deploy

- data/banis.json
This PR adds the following banis: alahnia, longer arti, longer rehras. It differentiates the two rehras and arti banis with different names.
- double-checking of line IDs
- 90 minutes
> feat: add more banis

- data/Sri Guru Granth Sahib Ji/0294.json
Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part1.
> fix(data): update id 8DPT to match physical proof

- data/Sri Guru Granth Sahib Ji/0262.json
Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part1.
> fix(data): line UR26 should be after WEC7, not 6JS7

- data/Sri Guru Granth Sahib Ji/0296.json
Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part1.
> fix(data): update id 29FG to match physical proof

- data/Sri Guru Granth Sahib Ji/0492.json
Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part2.
> fix(data): update id MF7N to match physical proof

- data/Sri Guru Granth Sahib Ji/0693.json
Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part2.
> fix(data): update id 54E4 to match physical proof

- data/Sri Guru Granth Sahib Ji/1412.json
> fix(data): update id 1SHF to match physical proof

- data/Sri Guru Granth Sahib Ji/0795.json
> fix(data): update id URWL to match physical proof

- data/Sri Guru Granth Sahib Ji/0837.json
> fix(data): update id BMAZ to match physical proof

- data/Sri Guru Granth Sahib Ji/0693.json
- data/Sri Guru Granth Sahib Ji/0694.json
> fix(data): move id 11YX into shabad 897

- data/Sri Guru Granth Sahib Ji/0957.json
https://gurbaninow.com/shabad/147
https://gurbaninow.com/shabad/TQX
Mangal + Sirlekh should not be in a separate Shabad.
> fix(data): combine shabad 147 and TQX

- data/Sri Guru Granth Sahib Ji/0947.json
https://gurbaninow.com/shabad/FNK
https://gurbaninow.com/shabad/FXF
Mangal + Sirlekh should not be in a separate Shabad.
> fix(data): combine shabad FNK and FXF

- data/Sri Guru Granth Sahib Ji/0658.json
https://gurbaninow.com/shabad/DNE
Shabad ID `DNE` contains two shabads. The second shabad was assigned ID `KHN`
> fix(data): split shabad DNE into KHN

- data/Sri Guru Granth Sahib Ji/1408.json
> fix(data): update id 2JZL to match physical proof

- data/Sri Guru Granth Sahib Ji/1406.json
> fix(data): update id FD4R to match physical proof

- data/Sri Guru Granth Sahib Ji/1404.json
> fix(data): update id ZET9 to match physical proof

- data/Sri Guru Granth Sahib Ji/1393.json
> fix(data): update id WM9Q to match physical proof

- data/Sri Guru Granth Sahib Ji/1361.json
> fix(data): update id EG3V to match physical proof

- data/Sri Guru Granth Sahib Ji/1262.json
> fix(data): update id 44PX to match physical proof

- data/Sri Guru Granth Sahib Ji/1252.json
> fix(data): update id 9Q3R to match physical proof

- data/Sri Guru Granth Sahib Ji/1242.json
> fix(data): update id DGEM to match physical proof

- data/Sri Guru Granth Sahib Ji/1205.json
> fix(data): update id JW70 to match physical proof

- data/Sri Guru Granth Sahib Ji/1170.json
> fix(data): update id HN59 to match physical proof

- data/Sri Guru Granth Sahib Ji/1158.json
> fix(data): update id J5XP to match physical proof

- data/Sri Guru Granth Sahib Ji/1099.json
> fix(data): update id BLW9 to match physical proof

- data/Sri Guru Granth Sahib Ji/1084.json
> fix(data): update id DACQ to match physical proof

- data/Sri Guru Granth Sahib Ji/1002.json
> fix(data): update id 9CYR to match physical proof

- data/Sri Guru Granth Sahib Ji/0964.json
> fix(data): update id KS4L to match physical proof

- data/Sri Guru Granth Sahib Ji/0959.json
> fix(data): update id 0QZF to match physical proof

- data/Sri Guru Granth Sahib Ji/0898.json
> fix(data): update id C9CH to match physical proof

- data/Sri Guru Granth Sahib Ji/1413.json
> fix(data): update id L8H3 to match physical proof

- data/Sri Guru Granth Sahib Ji/0040.json
Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part1.
> fix(data): update id V6SJ to match physical proof

- data/Sri Guru Granth Sahib Ji/0227.json
- data/Sri Guru Granth Sahib Ji/0410.json
- data/Sri Guru Granth Sahib Ji/1025.json
- data/Sri Guru Granth Sahib Ji/1030.json
- data/Sri Guru Granth Sahib Ji/1103.json
- data/Sri Guru Granth Sahib Ji/1330.json
- data/Sri Guru Granth Sahib Ji/1392.json
- data/Sri Guru Granth Sahib Ji/1404.json
Fixes many instances of `AMqr giq` to `AMqrgiq`
> fix(data): update instances of 'AMqrgiq' to match physical proof

- data/Sri Dasam Granth/0014.json
- data/Sri Dasam Granth/0030.json
- data/Sri Dasam Granth/0034.json
- data/Sri Dasam Granth/0035.json
- data/Sri Dasam Granth/0037.json
- data/Sri Dasam Granth/0712.json
Takes care of old lingering issues.
> Fix old Sri Dasam Granth corrections

- data/Ganj Nama Bhai Nand Lal Ji/01.json
- data/Ganj Nama Bhai Nand Lal Ji/04.json
- data/Ganj Nama Bhai Nand Lal Ji/05.json
- data/Ganj Nama Bhai Nand Lal Ji/06.json
- data/Ganj Nama Bhai Nand Lal Ji/07.json
- data/Ganj Nama Bhai Nand Lal Ji/10.json
- data/Ghazals Bhai Nand Lal Ji/13.json
- data/Ghazals Bhai Nand Lal Ji/17.json
- data/Ghazals Bhai Nand Lal Ji/19.json
- data/Ghazals Bhai Nand Lal Ji/20.json
- data/Ghazals Bhai Nand Lal Ji/21.json
- data/Ghazals Bhai Nand Lal Ji/23.json
- data/Ghazals Bhai Nand Lal Ji/26.json
- data/Ghazals Bhai Nand Lal Ji/27.json
- data/Ghazals Bhai Nand Lal Ji/30.json
- data/Ghazals Bhai Nand Lal Ji/32.json
- data/Ghazals Bhai Nand Lal Ji/33.json
- data/Ghazals Bhai Nand Lal Ji/36.json
- data/Ghazals Bhai Nand Lal Ji/40.json
- data/Ghazals Bhai Nand Lal Ji/48.json
- data/Ghazals Bhai Nand Lal Ji/49.json
- data/Ghazals Bhai Nand Lal Ji/53.json
- data/Ghazals Bhai Nand Lal Ji/56.json
- data/Ghazals Bhai Nand Lal Ji/58.json
- data/Ghazals Bhai Nand Lal Ji/64.json
- data/Jot Bigas Bhai Nand Lal Ji/1.json
- data/Zindagi Nama Bhai Nand Lal Ji/1.json
I checked for double spaces and triple spaces, etc. Then used the following regex to clean up in VS Code
Find:
```
("gurmukhi": \{\n +".+": ")(.*?)( ){2}(.*?)(")
```
Replace:
```
$1$2 $4$5
```
$2 and $4 are the remaining gurmukhi string. $1 and $5 are the json around it to find gurmukhi lines.
- I did not check for multiple gurmukhi lines. So if one line ID has two gurmukhi values, I did not check the second one. As far as I can tell, we don't have any line IDs with multiple sources yet.
Less than 10 minutes
> fix(data): remove duplicate whitespace

- data/Kabit Savaiye Bhai Gurdas Ji/235.json
> Update Shabad C5K - Lines EXK1, NZBB, H8R1, and RS3B per Bh Sewa Singh Source

- data/Sri Dasam Granth/0010.json
> fix(data): Change Yayya to open top in Jaap Sahib
